call "%~dp0\set_env.bat"

SET modules=(LIBBATCH KERNEL GUI MEDCOUPLING MED GEOM SMESH YACS JOBMANAGER HEXABLOCK HEXABLOCKPLUGIN NETGENPLUGIN GHS3DPLUGIN HEXOTICPLUGIN BLSURFPLUGIN ATOMGEN ATOMIC ATOMSOLV PYCALCULATOR CALCULATOR COMPONENT LIGHT PYLIGHT RANDOMIZER SIERPINSKY PYHELLO HELLO PARAVIS HYBRIDPLUGIN CONFIGURATION)

for %%i in %modules% do ( 
  RD /Q /S %SALOME_ROOT_DIR%\MODULES\%%i\RELEASE
)
